### ISSUE TITLE
handlebars is killing control...

### ISSUE THREAD

**Issue by naki357** [crlcu/multiselect#13]
Very nice control.  

We're running into problems when using Handlebars to render new sets of List Items in the left side Select list.  Handlebars abruptly replaces the items and doesn't care about the events that are hooked up to those items.  

...Is there a way we can Deactivate all of the multiSelect events or the control itself so we can cleanly reactivate it again once Handlebars has finished rendering new items in the left hand list.

**Comment by crlcu** [comment]
Hi @naki357 
I'm thinking to add a ``refresh`` method.
Could you explain a bit more detailed what you want to happen when the ``refresh`` method will be called ?

**Comment by crlcu** [comment]
Some changes were made to the plugin and I think the issue will not reproduce now.
Dynamically adding ``options`` to ``select`` element works fine now.

**Comment by Jogii** [comment]
The issue is still reproducible. Handlebars,js is used to populate data in the template in compile time.
for eg. i use hadlebars #each to loop over the response data fill the left hand side of multiselect. But once my DOM is ready and i initialise multiselect the data vanishes. :(  Alternately now i am appening the data to the multiselect and using Handlebars templating engine.
